module.exports = [
  { q: 'If %% had a sidekick superpower, what would it be?'},
  { q: 'If %% could time travel, who would they visit and why?'},
  { q: 'Why would %% justify killing someone?' },
  { q: 'What is %%\'s secret obsession?' },
  { q: 'If %% were to change their name, what would they change it to?'},
  { q: 'What really annoys %%?'},
  { q: 'What is %%\'s biggest fear?'},
  { q: 'If %% opened a restaurant what kind of food would they serve?'},
  { q: 'If %% could live anywhere where would they live?'},
  { q: 'If %% invented a new flavor of ice cream, what would it be called and what would be in it?'},
  { q: 'Describe %% in one word.'},
  { q: 'What is %%\'s biggest goal for the year?'},
  { q: 'What is the top item on %%\'s bucket list?'},
  { q: 'If %% could invent anything, what would it be?'},
  { q: 'What can\'t %% live without?'},
  { q: '%% never leaves home without?'},
  { q: 'What is one thing %% is really good at?'},
  { q: 'What does %% do to relax?'},
  { q: 'What is %%\'s most embarrassing moment?'},
  { q: 'If %% built a themed house, what would the theme be?'},
  { q: 'What is %%\'s favorite pass time?'},
  { q: 'What is %%\'s dream job?'},
  { q: 'Why would %% become famous?'},
  { q: 'What movie would %% be embarrassed to be caught watching?'},
  { q: 'What song would %% use to describe their life?'},
  { q: '%%'},
  { q: '%%'},
]
