module.exports = [
  { q: "If %% had a sidekick superpower, what would it be?"},
  { q: "If %% could time travel, who would they visit and why?"},
  { q: "Why would %% justify killing someone?'"},
  { q: "What is %%'s secret obsession?'"},
  { q: "If %% were to change their name, what would they change it to?"},
  { q: "What really annoys %%?"},
  { q: "What is %%'s biggest fear?"},
  { q: "If %% opened a restaurant what kind of food would they serve?"},
  { q: "If %% could live anywhere where would they live?"},
  { q: "If %% invented a new flavor of ice cream, what would it be called and what would be in it?"},
  { q: "Describe %% in one word."},
  { q: "What is %%'s biggest goal for the year?"},
  { q: "What is the top item on %%'s bucket list?"},
  { q: "If %% could invent anything, what would it be?"},
  { q: "What can't %% live without?"},
  { q: "%% never leaves home without?"},
  { q: "What is one thing %% is really good at?"},
  { q: "What does %% do to relax?"},
  { q: "What is %%'s most embarrassing moment?"},
  { q: "If %% built a themed house, what would the theme be?"},
  { q: "What is %%'s favorite pass time?"},
  { q: "What is %%'s dream job?"},
  { q: "Why would %% become famous?"},
  { q: "What movie would %% be embarrassed to be caught watching?"},
  { q: "What song would %% use to describe their life?"},
  { q: "Who would %% not want to get stuck in an elevator with?"},
  { q: "Why would %% get fired?"},
  { q: "What would %%'s presidential campaign slogan be?"},
  { q: "What was %% almost named but wasn't?"},
  { q: "If %% were in a horror film how would they die?"},
  { q: "How would %% become famous?"},
  { q: "What is %%'s guilty pleasure?"},
  { q: "What would %%'s alibi be that they would not want to confess to the police?"},
  { q: "What reality TV show would %% be on?"},
  { q: "What is %%'s secret talent?"},
  { q: "What is %%'s favorite food?"},
  { q: "If %% landed on the moon what would be the first thing they say?"},
  { q: "Why would %% get dumped by the love of their life?"},
  { q: "What is one thing %% wouldn't want their soul mate to know?"},
  { q: "What would %%'s excuse be walking out of a sperm donation building?"},
  { q: "%% will never throw this away."},
  { q: "What's an unexpected line on %%'s online dating profile?"},
  { q: "What is %%'s biggest regret?"},
  { q: "%% dreams about this but will never admit it?"},
  { q: "%% would die completing this item on their bucket list."},
  { q: "If %% could speak for 5 minutes on nation TV they would talk about?"},
  { q: "%% thinks about this when they fake looking focused in a class?"},
  { q: "%% thinks about this when they fake looking focused at church?"},
  { q: "Everyone thought %% would(/will) be _____ when they grew(/grow) up."},
  { q: "%% will never _____ in front of others."},
  { q: "What would %%'s wrestling name be?"},
  { q: "Where does %% draw the line?"},
  { q: "If %% had a time machine what major event would they try and change?"},
  { q: "If %% had a time machine who would they kill?"},
  { q: "If %% were a high school teacher what would they teach?"},
  { q: "Why would %% be wanted by Interpol?"},
  { q: "What decade would %% have preferred to be born?"},
  { q: "Why would %% object at a wedding?"},
  { q: "Why would %% betray their family?"},
  { q: "How would %% dispose of a body?"},
  { q: "If %% could make one thing illegal what would it be?"},
  { q: "Why would %% get expelled?"},
  { q: "Why would %% get kicked out of a movie theatre?"},
  { q: "Nothing offends %% more than _____."},
]
